local supporters = {
    "Upsidedowneye",
    "akip",
    "Blue eyes white dragon",
    "Jetison333",
    "breakfastninjas",
    "Izzabelle the Marrow beater",
    "Alodo",
    "the sauce",
    "Thyme",
    "Magentide",
    "DocJade",
    "ExclusiveOr",
    "Iterative Imp",
    "Survivor205",
    "juhelak",
    "Eric",
    "EulersApprentice",
    "Henry30389 the Marrow beater",
    "pheubel",
    "sibuech",
    "00Shiaw00",
    "Keyford",
    "Nueroplastic",
    "sejemsom",
    "green8751",
    "DoubLL",
    "Tiksta",
    "duhuhu_",
    "Frogbottom",
    "yiffweed",
    "NovaLiminal",
    "BaconDragon",
    "adelrik12",
    "JakeyGoat",
    "Rvdy",
    "JWop",
    "Laramere",
    "sassxolotl",
    "INFERNOO",
    "thyaxis",
    "Runelt99 The Slayer of Exfret",
    "MrE",
    "DavidPT",
    "Our all powerful lord and saviour Exfret",
    "Serginov",
    "Terold",
    "TMTIME",
    "Ashindigo",
    "Oxtylxq",
    "forsaken75",
    "twilightthepony",
}

return supporters